# Generated by Django 4.2.10 on 2024-02-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.music'),
        ),
    ]
